[client]
showSidebarNavigation = false

[theme]
primaryColor = "#0A84FF"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#E0E0E0"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = false

font = 'Calibri'

